### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by martinhansdk** [kallaballa/libnfporb#11]
Would you accept a pull request that adds regression tests to the project?

I am thinking about simply adding the result of running the current examples in the data directory as reference files and have a test check against them. I'm assuming that you must have looked closely at all of those outputs so they constitute a pretty good set of correct results. Not only would it catch issues like the one with the non-working boost version, it would also help me greatly when making sure that the library works properly on Visual Studio.

I'm thinking about using catch2 as the test library as that is a very small single header only dependency.

Also, would you be opposed to me switching the build system from make to cmake? Cmake has the advantage of being cross platform.

**Comment by kallaballa** [comment]
I'd gladly accept it
