### ISSUE TITLE
unable to complete outer loop

### ISSUE THREAD

**Issue by martinhansdk** [kallaballa/libnfporb#12]
Running `testgen.sh` ends with an error:

    #### Running case data/generated/Z.wkt data/generated/2.wkt: ./testgen.sh: line 16: 11971 Aborted                 build/examples/nfp $file1 $file2 &>> testgen.log
    Fail

`testgen.log` contains the following message:

    terminate called after throwing an instance of 'std::runtime_error'
      what():  Unable to complete outer nfp loop

**Comment by kallaballa** [comment]
I can't reproduce with the current code:

    > examples/nfp data/generated/Z.wkt data/generated/2.wkt
    > echo $?
    0
