### ISSUE TITLE
Bad assumptions 

### ISSUE THREAD

**Issue by garciagimenezangel** [kallaballa/libnfporb#13]
Hi kallaballa, thanks a lot for your efforts coding this. I have a question regarding your note about the bad assumptions of the paper that inspired the NFP generator. If I'm not wrong, it is E.K. Burke et al. 2006. ¿Do you mean that it is necessary to make additional assumptions, on top of what can be read in the paper, to complete the NFP generator? Is the paper by Bennell & Song free of those types of issue? Thanks a lot!

**Comment by kallaballa** [comment]
yes, it is E.K. Burke et al. 2006.

> Do you mean that it is necessary to make additional assumptions, on top of what can be read in the paper, to complete the NFP generator?

yes

> Is the paper by Bennell & Song free of those types of issue? 

I don't know the paper.

One example for a bad assumption is, that the paper proposes to use the lowest-y point of polygon A as reference point. _BUT_ there can be more than one point lowest and you have to take the rightmost or the algorithm will not complete

**Comment by garciagimenezangel** [comment]
Ok, thanks! The paper by Bennell & Song, I mean the one that you state that you are using as reference now (https://eprints.soton.ac.uk/36850/1/CORMSIS-05-05.pdf) In your opinion, is it a more robust approach?

**Comment by kallaballa** [comment]
Oh, that one. I'm not sure yet.
