### ISSUE TITLE
Running nfp without boost and libgmp

### ISSUE THREAD

**Issue by petrasvestartas** [kallaballa/libnfporb#14]
Hi, 

In the project description it is written:
_The library has two dependencies: Boost Geometry and libgmp. You need to install those first before building. Note that building is only required for the examples. The library itself is header-only._

Does it mean that it is possible to run your library in console application without boost and libgmp?
If Yes is it possible to get a source code without referencing these main libraries.

If not I would like to ask if the library is only  contains of one file:
https://github.com/kallaballa/libnfporb/blob/master/src/libnfporb.hpp

**Comment by kallaballa** [comment]
> Does it mean that it is possible to run your library in console application without boost and libgmp?

No.. you definitely need boost geometry and libgmp.

> If not I would like to ask if the library is only contains of one file

exactly
