### ISSUE TITLE
generateNFP only returns singular points

### ISSUE THREAD

**Issue by Papooch** [kallaballa/libnfporb#19]
Hello, kallaballa, I hope you are still active, I ran into an issue with this library where the function generateNFP does not return the no fit polygon, only some singular points. When I run your example code on the example geometry, I get this:

data/handcrafted/rect:
![image](https://user-images.githubusercontent.com/46406259/77108975-6e96d600-6a23-11ea-92d9-8d15437fc48e.png)

data/handcrafted/jigsaw:
![image](https://user-images.githubusercontent.com/46406259/77109293-f54bb300-6a23-11ea-92c6-8ef56a0dc8a1.png)

The same happens when I try simple custom geometry
![image](https://user-images.githubusercontent.com/46406259/77110253-8ff8c180-6a25-11ea-8af2-0477a106b256.png)

I'm on Windows 10, compiling with Visual Studio 2017, Boost version 1.72 if that helps.

I wanted to use it as a python extension for a scientific research project at my university, but this is really holding me back. Do you have any idea what could be the problem? Thanks!

**Comment by Papooch** [comment]
Okay, so the problem was somewhere in Boost, as discussed here: https://github.com/kallaballa/libnfporb/issues/7 I tried to **install boost version 1.65** and it worked.

![image](https://user-images.githubusercontent.com/46406259/77116423-79a43300-6a30-11ea-82d9-91a8fb276aec.png)

Please, add to the readme that boost > 1.65 is not supported.

**Comment by kallaballa** [comment]
Thx for figuring that out! Sorry for the long wait...
I'm currently using 1_76_0 and it works but i will add to the readme that the recommended boost version is 1.65

**Comment by kallaballa** [comment]
done
