### ISSUE TITLE
Runtime error: No touching points with certain simple geometry

### ISSUE THREAD

**Issue by Papooch** [kallaballa/libnfporb#20]
In some obscure cases, the program throws a runtime error stating that "No touching points found". One example of such shape is: 
`
POLYGON((181 180,181 331,31 331,31 31,181 31,181 180))
`
(It does not matter if it serves as A or B)
But as soon as I change it to
`
POLYGON((**180** 180,181 331,31 331,31 31,181 31,**180** 180))
`
It miraculously works and finds a valid NFP!

I tried to examine the code but I am of the impression that there must be some error in Boost.geometry, especially bg::intersects.

(Boost version 1.65)

**Comment by kallaballa** [comment]
Sorry for the long wait. I am on it

**Comment by kallaballa** [comment]
I tried to reproduce using following wkt:
A: POLYGON((181 180,181 331,31 331,31 31,181 31,181 180))
B: POLYGON((500 300,500 200,600 200,600 300))

And it generates fine (green=A, red=B, blue=nfp)
![notouchingpoints-nfp](https://user-images.githubusercontent.com/287266/132453828-51092748-f3b4-498e-afd8-ef35b0321aa5.png)

That said, I found another test case that exhibits similar behaviour:
A: POLYGON ((-192 -320, -192 -64, -64 -64, -61 -193, 25 -320, 111 -320, 228 -320, 320 -150, 320 96, 320 1344, 64 1344, 64 1472, 704 1472, 704 1344, 512 1344, 512 89, 512 -195, 315 -448, 97 -448, 26 -448, -120 -384, -192 -320))
B: POLYGON ((192 128, 192 448, 320 447, 325 284, 517 128, 713 128, 896 128, 1088 255, 1088 377, 1088 475, 972 579, 785 629, 583 678, 368 740, 192 926, 192 1088, 192 1271, 467 1472, 715 1472, 821 1472, 1074 1407, 1216 1344, 1216 1024, 1088 1024, 1071 1193, 892 1344, 710 1344, 550 1344, 384 1220, 384 1102, 387 1011, 515 901, 722 842, 911 797, 1111 738, 1281 555, 1280 403, 1280 203, 995 0, 714 0, 588 0, 327 63, 192 128))

Fails with `Internal Error: Slide resulted in overlap`. But when i change 1281 in polygon B to 1280, it works.
Anyway, I am not entirely sure those bugs are related, yet. 

Could you please try to reproduce your problem with the current HEAD?

**Comment by kallaballa** [comment]
The problem had to do with negative coordinates. From 9f1f6d3419e87fae0c57a460947e0f8be3117501 on the polygons are translated into positive coordinate space just far enough, so that there are never any negative coordinates.
