### ISSUE TITLE
Why some results seem to miss a part?

### ISSUE THREAD

**Issue by Naimad1CZ** [kallaballa/libnfporb#21]
Hi, I would like to know, why in some cases there is a line segment missing in NFP, e.g. in data/handcrafted/crossing:

![image](https://user-images.githubusercontent.com/35201314/118385352-59f5a400-b60e-11eb-807a-9d42bdbfde83.png)

(I would say that the result should be like this:)
![image](https://user-images.githubusercontent.com/35201314/118409229-a29e7300-b689-11eb-9bb5-e697a9d95d83.png)

However, this (the first image) NPF result is even in the golden.wkt file, so it's probably intended, but I don't know why - does it have something to do with floating point arithmetics?

The thing is that in my constructed test [I'm trying to change the code so it generates also Inner Fit Polygons (basically the thing that is calculated for holes of polygon A when computing NFP), and was constructing some cases to know if it's safe to compute only this] there should be a line segment in the "bottom part" (which is fulfilled) and also in the "upper part" (which isn't).

Polygon representation + NFP:
`POLYGON((0 0,0 100,100 100,100 0), (30 30,30 5,95 5,95 85,30 85,30 60,50 60,50 50,40 55,40 35,50 40,50 30))`
`POLYGON((60 35,70 40,70 30,80 30,80 60,70 60,70 50,60 55))`
![image](https://user-images.githubusercontent.com/35201314/118385683-7ba45a80-b611-11eb-849a-16cb0d7d6549.png)

"Should be:"
![image](https://user-images.githubusercontent.com/35201314/118385735-efdefe00-b611-11eb-8205-330eff8adbd8.png)

Here is a case without inner holes, with the same issue:
`POLYGON((30 30,30 5,95 5,95 0,0 0,0 100,95 100,95 85,30 85,30 60,50 60,50 50,40 55,40 35,50 40,50 30))`
`60 35,70 40,70 30,80 30,80 60,70 60,70 50,60 55`
![image](https://user-images.githubusercontent.com/35201314/118385710-9aa2ec80-b611-11eb-905e-7b8f8dcd0308.png)

PS: Anyway, thank you very much for creating this library! :)

**Comment by kallaballa** [comment]
As stated in the readme this library is not finished and I don't have time to work on it at the moment :)
I hope you'll find a way and send a pull request! anyway, your hunch may be right about floating point arithmetic. you can always try to define "LIBNFP_USE_RATIONAL" to avoid floating point. also, what version of boost geometry are you using?

**Comment by Naimad1CZ** [comment]
The thing is that I didn't manage to install libgmp on Windows (specifically didn't manage to install m4 in a way that configure of libgmp would be able to use it), so I can't check if defining "LIBNFP_USE_RATIONAL" would fix this.

If I gave it quite more time, I might be able to somehow install it on Windows or Ubuntu on VirtualBox, but I'm writing an irregular online bin packing/nesting algorithm for Bachelor's thesis, so I don't have much time spared and I don't want to rely on dependencies that are hard to install. [btw. I'm not sure about licencing - can I release source code of my thesis (Python code using modified libnfporb via pybind) under MIT, or do I have to licence modified libnfporb under GPL v3 and can licence the rest under MIT, or do I have to licence whole source code under GPL v3?]

Boost version 1.65.0.

**Comment by kallaballa** [comment]
You have to release it under GPLv3 if you are linking to the code. And also, you can not change the license of libnfporb.

**Comment by kallaballa** [comment]
I resumed work on libnfporb. I am on it :)

**Comment by kallaballa** [comment]
your first example now generates correctly since 6d8b89babc63847be6b230b04150d3bbd5b59ca1

**Comment by kallaballa** [comment]
I can verify the problem with the second example. trying to understand...

**Comment by kallaballa** [comment]
I can verify the problem with the second example. trying to understand...

**Comment by kallaballa** [comment]
fixed
