### ISSUE TITLE
Edge case false positive degenerate case

### ISSUE THREAD

**Issue by Naimad1CZ** [kallaballa/libnfporb#22]
When having those 2 polygons:
`POLYGON((20 10,20 30,30 30,30 10,40 20,40 30,30 40,60 40,60 80,0 80,20 40,10 30,10 20))`
`POLYGON((50 30,50 20,60 20,60 30))`
The resulting NFP consists of 1 big loop (correct) and 1 degenerate point (wrong).

![image](https://user-images.githubusercontent.com/35201314/118414526-5d883a00-b6a5-11eb-9e8e-40de662d9e70.png)

I can see why it's selected - all vertices of polygon B (sliding polygon) are touching vertices of the polygon A, but everything else (except one edge) from polygon B is directly inside the polygon A.

**Comment by kallaballa** [comment]
The paper i based this on is incomplete when it comes to edge-cases with parallel lines. <strike>i tried to improvise but wasn't able to cover it all. </strike> -> a91f1ae12ba28455e54c076e9be757b9be888201 seems to work except for this issue

**Comment by kallaballa** [comment]
I am on it :)

**Comment by kallaballa** [comment]
fixed
