### ISSUE TITLE
Big files cause a sever performance penalty

### ISSUE THREAD

**Issue by gloryXmj** [kallaballa/libnfporb#26]
Here is my POLYGON data
POLYGON((55.3674 4.06366,58.0765 4.74094,59.939 6.60345,60.2777 6.43413,62.1402 7.78869,62.8175 7.78869,65.1879 9.31256,
66.7118 9.82052,68.5743 11.5137,69.0823 11.3444,69.7094 11.8147,71.0464 12.1233,72.9505 12.5241,75.0085 12.445,77.0403 1
2.3603,78.5642 11.3444,79.9187 11.1751,81.6119 9.82052,82.4585 9.82052,82.9665 9.31256,83.4744 9.31256,83.8131 8.80461,8
5.6756 8.12733,85.8449 7.61937,86.1835 7.78869,87.8767 6.77277,88.0037 6.79817,88.0461 6.77277,88.7782 6.91921,90.7119 6
.11351,90.8277 5.97455,91.2631 5.2489,92.279 5.2489,93.295 4.74094,94.8188 4.74094,95.6654 4.23298,98.7132 3.55571,98.80
99 3.57183,98.8825 3.55571,99.7659 3.70294,100.576 3.21707,103.623 3.21707,103.793 3.38639,104.019 3.49927,104.301 3.217
07,105.147 3.21707,105.768 3.52749,106.333 3.38639,106.366 3.42025,106.502 3.38639,106.812 3.69681,107.518 3.55571,107.6
1 3.5711,107.687 3.55571,111.751 4.23298,112.259 4.74094,114.968 5.2489,116.492 6.26482,117.508 6.26482,121.571 8.29665,
122.079 8.29665,124.111 9.48188,126.312 10.6671,126.331 10.7047,126.99 10.8364,126.99 11.3444,127.836 11.3444,132.408 13
.8842,134.948 15.7467,137.318 18.2865,138.673 18.9638,141.382 22.1808,141.72 23.0274,143.466 24.3079,143.583 24.382,143.
605 24.4093,144.26 24.8899,144.712 25.793,144.937 26.0752,144.876 26.1223,144.937 26.2445,137.487 32.0014,137.068 32.141
1,136.81 32.34,136.641 32.2836,136.471 32.34,135.625 33.5252,133.762 34.5411,132.069 36.065,130.715 36.573,126.651 39.28
21,124.28 41.1446,122.079 41.8219,121.802 42.0374,121.741 42.1605,121.588 42.2042,120.555 43.0071,119.539 43.0071,118.35
4 43.6844,115.476 44.1923,114.799 44.7003,112.428 44.7003,112.089 45.2083,109.719 45.3776,108.872 45.7162,106.333 45.800
9,103.962 45.8855,103.939 45.8807,103.793 45.8855,94.9881 44.023,89.4006 41.4832,88.0461 40.4673,86.8608 40.1287,85.1676
 38.6048,84.9607 38.5296,84.4903 38.4355,84.4313 38.337,83.3051 37.9275,83.3051 37.5889,82.9665 37.3349,81.4426 36.573,8
0.2574 36.065,78.9028 35.0491,76.7017 34.0332,75.8551 34.0332,74.3312 33.0173,72.4687 33.0173,71.9607 32.5093,68.5743 32
.5093,64.8493 34.0332,64.3413 34.8798,62.9868 35.2184,62.8175 35.5571,59.2347 37.1148,58.2942 37.6373,56.722 38.6048,55.
8754 38.6048,55.1981 39.1128,52.997 39.6207,52.6583 40.1287,51.6424 40.6366,50.7958 40.6366,50.4572 41.1446,49.7799 41.1
446,49.1026 41.6526,44.023 43.0071,41.9065 43.1764,39.9594 43.3458,39.8933 43.3375,39.79 43.3458,37.0809 43.0071,36.573
42.3298,36.065 42.3298,35.7264 42.8378,35.5676 42.8219,35.5571 42.8378,34.8798 42.7531,34.0332 42.6685,33.6945 42.1605,3
2.5093 42.1605,31.3241 41.6526,30.9854 41.1446,28.9536 41.1446,27.505 40.3544,26.7525 40.1287,26.5831 40.1287,26.0752 39
.6207,24.8899 39.4514,21.6729 37.9275,19.9797 36.573,19.4717 36.573,18.6251 35.5571,15.2387 33.8639,14.3921 33.0173,10.8
364 30.9854,7.95801 28.4456,7.61937 28.4456,6.94209 27.4297,6.26482 27.2604,2.53979 23.5354,3.04775 23.3661,3.04775 23.0
274,1.69319 22.3502,1.52387 21.3342,0 20.149,0 19.8104,1.18524 19.1331,1.52387 18.6251,1.35455 18.1172,7.95801 11.5137,9
.98984 9.98984,12.8683 8.63529,14.2228 7.28073,15.5774 6.77277,18.7944 4.4023,19.641 4.23298,19.9797 3.72503,21.8422 2.8
7843,23.874 2.37047,24.2127 2.53979,26.4138 1.69319,27.2604 1.69319,28.107 1.18524,28.2763 1.18524,30.4775 1.01592,31.07
01 1.18524,31.3241 1.18524,31.4934 1.01592,31.1548 0.677278,32.5093 0.16932,32.6529 0.180363,32.6786 0.16932,34.7503 0.3
28679,36.065 0,40.4673 0,42.9301 0.492565,43.8537 0.338639,43.896 0.359804,44.023 0.338639,44.7003 0.677278,47.0708 0.67
7278,55.3674 4.06366)) 

The following is the output of my error after turning on NFP_DEBUG
![image](https://user-images.githubusercontent.com/55737309/150707590-287c0adb-d778-4b75-8778-f21e2d84c137.png)

Can you help me see what's the problem?

**Comment by kallaballa** [comment]
you are using the exact same (above) polygon for pA and pB?

**Comment by gloryXmj** [comment]
It's like this, I'm using two graphics that are exactly the same.

**Comment by kallaballa** [comment]
alright. i understand. but could you please paste the polygon data in code tags again? The way it is now i have to format it by hand.

**Comment by gloryXmj** [comment]
`POLYGON((55.3674 4.06366,58.0765 4.74094,59.939 6.60345,60.2777 6.43413,62.1402 7.78869,62.8175 7.78869,65.1879 9.31256,
66.7118 9.82052,68.5743 11.5137,69.0823 11.3444,69.7094 11.8147,71.0464 12.1233,72.9505 12.5241,75.0085 12.445,77.0403 1
2.3603,78.5642 11.3444,79.9187 11.1751,81.6119 9.82052,82.4585 9.82052,82.9665 9.31256,83.4744 9.31256,83.8131 8.80461,8
5.6756 8.12733,85.8449 7.61937,86.1835 7.78869,87.8767 6.77277,88.0037 6.79817,88.0461 6.77277,88.7782 6.91921,90.7119 6
.11351,90.8277 5.97455,91.2631 5.2489,92.279 5.2489,93.295 4.74094,94.8188 4.74094,95.6654 4.23298,98.7132 3.55571,98.80
99 3.57183,98.8825 3.55571,99.7659 3.70294,100.576 3.21707,103.623 3.21707,103.793 3.38639,104.019 3.49927,104.301 3.217
07,105.147 3.21707,105.768 3.52749,106.333 3.38639,106.366 3.42025,106.502 3.38639,106.812 3.69681,107.518 3.55571,107.6
1 3.5711,107.687 3.55571,111.751 4.23298,112.259 4.74094,114.968 5.2489,116.492 6.26482,117.508 6.26482,121.571 8.29665,
122.079 8.29665,124.111 9.48188,126.312 10.6671,126.331 10.7047,126.99 10.8364,126.99 11.3444,127.836 11.3444,132.408 13
.8842,134.948 15.7467,137.318 18.2865,138.673 18.9638,141.382 22.1808,141.72 23.0274,143.466 24.3079,143.583 24.382,143.
605 24.4093,144.26 24.8899,144.712 25.793,144.937 26.0752,144.876 26.1223,144.937 26.2445,137.487 32.0014,137.068 32.141
1,136.81 32.34,136.641 32.2836,136.471 32.34,135.625 33.5252,133.762 34.5411,132.069 36.065,130.715 36.573,126.651 39.28
21,124.28 41.1446,122.079 41.8219,121.802 42.0374,121.741 42.1605,121.588 42.2042,120.555 43.0071,119.539 43.0071,118.35
4 43.6844,115.476 44.1923,114.799 44.7003,112.428 44.7003,112.089 45.2083,109.719 45.3776,108.872 45.7162,106.333 45.800
9,103.962 45.8855,103.939 45.8807,103.793 45.8855,94.9881 44.023,89.4006 41.4832,88.0461 40.4673,86.8608 40.1287,85.1676
 38.6048,84.9607 38.5296,84.4903 38.4355,84.4313 38.337,83.3051 37.9275,83.3051 37.5889,82.9665 37.3349,81.4426 36.573,8
0.2574 36.065,78.9028 35.0491,76.7017 34.0332,75.8551 34.0332,74.3312 33.0173,72.4687 33.0173,71.9607 32.5093,68.5743 32
.5093,64.8493 34.0332,64.3413 34.8798,62.9868 35.2184,62.8175 35.5571,59.2347 37.1148,58.2942 37.6373,56.722 38.6048,55.
8754 38.6048,55.1981 39.1128,52.997 39.6207,52.6583 40.1287,51.6424 40.6366,50.7958 40.6366,50.4572 41.1446,49.7799 41.1
446,49.1026 41.6526,44.023 43.0071,41.9065 43.1764,39.9594 43.3458,39.8933 43.3375,39.79 43.3458,37.0809 43.0071,36.573
42.3298,36.065 42.3298,35.7264 42.8378,35.5676 42.8219,35.5571 42.8378,34.8798 42.7531,34.0332 42.6685,33.6945 42.1605,3
2.5093 42.1605,31.3241 41.6526,30.9854 41.1446,28.9536 41.1446,27.505 40.3544,26.7525 40.1287,26.5831 40.1287,26.0752 39
.6207,24.8899 39.4514,21.6729 37.9275,19.9797 36.573,19.4717 36.573,18.6251 35.5571,15.2387 33.8639,14.3921 33.0173,10.8
364 30.9854,7.95801 28.4456,7.61937 28.4456,6.94209 27.4297,6.26482 27.2604,2.53979 23.5354,3.04775 23.3661,3.04775 23.0
274,1.69319 22.3502,1.52387 21.3342,0 20.149,0 19.8104,1.18524 19.1331,1.52387 18.6251,1.35455 18.1172,7.95801 11.5137,9
.98984 9.98984,12.8683 8.63529,14.2228 7.28073,15.5774 6.77277,18.7944 4.4023,19.641 4.23298,19.9797 3.72503,21.8422 2.8
7843,23.874 2.37047,24.2127 2.53979,26.4138 1.69319,27.2604 1.69319,28.107 1.18524,28.2763 1.18524,30.4775 1.01592,31.07
01 1.18524,31.3241 1.18524,31.4934 1.01592,31.1548 0.677278,32.5093 0.16932,32.6529 0.180363,32.6786 0.16932,34.7503 0.3
28679,36.065 0,40.4673 0,42.9301 0.492565,43.8537 0.338639,43.896 0.359804,44.023 0.338639,44.7003 0.677278,47.0708 0.67
7278,55.3674 4.06366))`

**Comment by kallaballa** [comment]
thx!

when i try to generate the nfp like this
   
    examples/nfp data/handcrafted/issue26/A.wkt data/handcrafted/issue26/B.wkt
    
i get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Polygon A is invalid: Geometry has invalid self-intersections. A self-intersection point was found at (34.7797, 0.3); method: i; operations: u/i; segment IDs {source, multi, ring, segment}: {0, -1, -1, 235}/{0, -1, -1, 57}
Aborted (core dumped)
```

Are you correcting (e.g: bg::correct(p)) the polygon before generating?

Investigating...

**Comment by kallaballa** [comment]
also, what boost version are you using?

**Comment by gloryXmj** [comment]
> also, what boost version are you using?

boost  Version 1.65

**Comment by kallaballa** [comment]
Your data is invalid. Using boost 1.76 I get the following error message: 

    terminate called after throwing an instance of 'std::runtime_error'
    what():  Polygon A is invalid: Geometry has invalid self-intersections. A self-intersection point was found at (34.7797, 0.3); method: i; operations: u/i; segment IDs {source, multi, ring, segment}: {0, -1, -1, 235}/{0, -1, -1, 57}
    Aborted (core dumped)

This is what your polygon looks like:
![bla](https://user-images.githubusercontent.com/287266/151118264-cafa519e-d6f0-49a2-bcb3-3874755247d8.png)

**Comment by gloryXmj** [comment]
thx !

I have upgraded the boost version to 1.76 and recompiled the test, the results are the same as before, and my graph should not have self-intersection.
Below is the shape of my graph: 
![image](https://user-images.githubusercontent.com/55737309/151301012-1c99f485-7541-46a0-9087-605b16436ce3.png)
Debug output ifs.svg I uploaded via attachment 
![ifs](https://user-images.githubusercontent.com/55737309/151301390-a933d18f-777f-4b69-b4a1-45ffe92b12bb.svg)

**Comment by kallaballa** [comment]
could you attach your wkt file instead of pasting it?

**Comment by gloryXmj** [comment]
> could you attach your wkt file instead of pasting it?
This is the data of the graph. I saved the graph as kwt. There is no self-intersection but there is no output.
[shape1.pdf](https://github.com/kallaballa/libnfporb/files/8020384/shape1.pdf)
Since the wkt file cannot be uploaded, I changed the file suffix to pdf. When you receive the file, you need to manually change the file suffix to wkt

**Comment by gloryXmj** [comment]
> > could you attach your wkt file instead of pasting it?
> > This is the data of the graph. I saved the graph as kwt. There is no self-intersection but there is no output.
> > [shape1.pdf](https://github.com/kallaballa/libnfporb/files/8020384/shape1.pdf)
> > Since the wkt file cannot be uploaded, I changed the file suffix to pdf. When you receive the file, you need to manually change the file suffix to wkt

sorry ！
I get the output data but its computation time is much longer than I expected, is there any way to speed up the computation?

**Comment by kallaballa** [comment]
are you still using NFP_DEBUG? Are you maybe using  LIBNFP_USE_RATIONAL? Apart from that I fear it might simply be slow. This library is far from perfect :)

**Comment by kallaballa** [comment]
Since there actually is no issue I am closing this. Please feel free to create a new issue to discuss performance enhancements.

**Comment by gloryXmj** [comment]
thx！
I have turned off NFP_DEBUG for computational efficiency. When I was calculating the graph below, I was prompted Unable to complete outer nfp loop: 1 . Of course my pA and pB are still the same.
![image](https://user-images.githubusercontent.com/55737309/152940758-60a6a5d2-dbf4-4a19-bff6-526121019d70.png)
My graphic data is uploaded with pdf suffix as above, you need to manually modify it to wkt
[shape1.pdf](https://github.com/kallaballa/libnfporb/files/8021767/shape1.pdf)

look forward to your answer

**Comment by kallaballa** [comment]
Once i removed windows line-endings from the file (using dos2unix) the nfp generated fine but took a _very_ long time.
![bla](https://user-images.githubusercontent.com/287266/153029978-2256da5e-9b0a-4bd8-b38c-f41ce2be3f03.png)

**Comment by kallaballa** [comment]
Is simplifying your shapes an option?
https://www.boost.org/doc/libs/1_65_0/libs/geometry/doc/html/geometry/reference/algorithms/simplify/simplify_3.html

**Comment by kallaballa** [comment]
This code returns in under a second and generates the following nfp (please pull master before trying this!)

```cpp
#include "../src/libnfporb.hpp"

int main(int argc, char** argv) {
  using namespace libnfporb;

	polygon_t pA;
	polygon_t pB;

	polygon_t pAsimple;
	polygon_t pBsimple;

	//read polygons from wkt files
	read_wkt_polygon(argv[1], pA);
	read_wkt_polygon(argv[2], pB);

	boost::geometry::simplify(pA, pAsimple, 0.5);
	boost::geometry::simplify(pB, pBsimple, 0.5);

	std:: cerr << boost::geometry::num_points(pA) << std::endl;
	std:: cerr << boost::geometry::num_points(pAsimple) << std::endl;

  //generate NFP of polygon A and polygon B and check the polygons for validity.
  //When the third parameters is false validity check is skipped for a little performance increase
	nfp_t nfp = generate_nfp(pAsimple, pBsimple, true);

	//write and svg containing pA, pB and NFP
	write_svg("nfp.svg",pAsimple,pBsimple,nfp);
	return 0;
}
```
![bla](https://user-images.githubusercontent.com/287266/153036401-3afd69b9-8e19-4fbb-9dfe-2b93d5988901.png)

**Comment by gloryXmj** [comment]
> This code returns in under a second and generates the following nfp (please pull master before trying this!)
> 
> ```c++
> #include "../src/libnfporb.hpp"
> 
> int main(int argc, char** argv) {
>   using namespace libnfporb;
> 
> 	polygon_t pA;
> 	polygon_t pB;
> 
> 	polygon_t pAsimple;
> 	polygon_t pBsimple;
> 
> 	//read polygons from wkt files
> 	read_wkt_polygon(argv[1], pA);
> 	read_wkt_polygon(argv[2], pB);
> 
> 	boost::geometry::simplify(pA, pAsimple, 0.5);
> 	boost::geometry::simplify(pB, pBsimple, 0.5);
> 
> 	std:: cerr << boost::geometry::num_points(pA) << std::endl;
> 	std:: cerr << boost::geometry::num_points(pAsimple) << std::endl;
> 
>   //generate NFP of polygon A and polygon B and check the polygons for validity.
>   //When the third parameters is false validity check is skipped for a little performance increase
> 	nfp_t nfp = generate_nfp(pAsimple, pBsimple, true);
> 
> 	//write and svg containing pA, pB and NFP
> 	write_svg("nfp.svg",pAsimple,pBsimple,nfp);
> 	return 0;
> }
> ```
> 
> ![bla](https://user-images.githubusercontent.com/287266/153036401-3afd69b9-8e19-4fbb-9dfe-2b93d5988901.png)

sorry ！
After I pulled the code from the master branch, there was a problem with the compilation

Error message：

std::vector<libnfporb::TranslationVector,std::allocator<_Ty>>::push_back(const libnfporb::TranslationVector &)": cannot convert argument 1 from "initializer list" to "libnfporb::TranslationVector &&"
         with
         [
             _Ty=libnfporb::TranslationVector
         ]
d:\workspace\kwstudiogitlit\src\nccutting\nccutting\qtnfps\third_parts\libnfp\src\algo/find_feasible.hpp(69): note: The reason is as follows: cannot convert from "initializer list" to "libnfporb::TranslationVector"
d:\workspace\kwstudiogitlit\src\nccutting\nccutting\qtnfps\third_parts\libnfp\src\algo/find_feasible.hpp(69): note: no constructor can accept source type, or constructor overload resolution is ambiguous

About ten of them are in the same file

**Comment by kallaballa** [comment]
What compiler are you using?

**Comment by gloryXmj** [comment]
> What compiler are you using?

msvc2015

**Comment by kallaballa** [comment]
libnfporb needs c++17 support.
https://stackoverflow.com/questions/41308933/how-to-enable-c17-compiling-in-visual-studio

**Comment by gloryXmj** [comment]
thx!
According to your plan, I have successfully obtained the desired result and it is very fast.
This library is really a great tool.

**Comment by kallaballa** [comment]
Awesome! Thx!
