### ISSUE TITLE
inner nfp without output 

### ISSUE THREAD

**Issue by gloryXmj** [kallaballa/libnfporb#27]
I found that the library can't generate the internal nfp directly so I constructed a polygon with a hole but the internal nfp is not generated when I test it . But I can generate using hole3 from test data
Below is my test data
[pB.pdf](https://github.com/kallaballa/libnfporb/files/8114850/pB.pdf)
[pA.pdf](https://github.com/kallaballa/libnfporb/files/8114851/pA.pdf)

what happened?

**Comment by voidBunny** [comment]
Your pdf file cannot display the content.

**Comment by kallaballa** [comment]
Sorry for the long delay. 
Yes. the PDFs seem to be broken. thx @voidBunny
