### ISSUE TITLE
The resulting polygon is shifted

### ISSUE THREAD

**Issue by intractabilis** [kallaballa/libnfporb#30]
Consider the following code:
```
    auto poly1 = libnfporb::polygon_t{};
    poly1.outer().push_back({12, 0});
    poly1.outer().push_back({0, 12});
    poly1.outer().push_back({-12, 0});
    poly1.outer().push_back({0, -12});

    auto poly2 = libnfporb::polygon_t{};
    poly2.outer().push_back({10, 10});
    poly2.outer().push_back({-10, 10});
    poly2.outer().push_back({-10, -10});
    poly2.outer().push_back({10, -10});

    auto nfp = generate_nfp(poly1, poly2, true);
```
Here is the result:
![scene](https://user-images.githubusercontent.com/45959195/171161198-6b329d0d-2f9e-4ea6-8a08-e638179275df.png)

The green dot is the coordinates' origin. I would expect the NFP also to be located around the green dot.

**Comment by kallaballa** [comment]
That is currently a limitation. libnfporb shifts the nfp into positive coordinate space. didn't think that might cause problems see #20. Let me see what i can do about it :)

**Comment by kallaballa** [comment]
I think i fixed it in this branch: https://github.com/kallaballa/libnfporb/tree/issue30
Could you give it a try?

**Comment by kallaballa** [comment]
could you open issue about the performance comments you had in your email? I can't at the moment answer gmail-emails

**Comment by kallaballa** [comment]
thx!

**Comment by intractabilis** [comment]
The legal department gave the green light, but asked me to share the data privately. Can I create an issue, but send you the data for the issue over gmail? I would even create in this case a short program that tests the performance.

**Comment by kallaballa** [comment]
alright

**Comment by intractabilis** [comment]
Still seems incorrect. Since the source polygons have central symmetry, obviously, their Minkowski difference also has to have central symmetry. I.e. the NFP's center should be where the green dot is.

![scene](https://user-images.githubusercontent.com/45959195/171926413-b5fbf7f5-5d6a-4b5e-8abf-65c603060acb.png)

**Comment by kallaballa** [comment]
Dang... I'll look into it!

**Comment by kallaballa** [comment]
I analyzed the situation and found out that the result of your [test](https://github.com/kallaballa/libnfporb/tree/master/data/handcrafted/issue30) was correct from the beginning. Because illustrating in text seemed tedious I created a [video](https://vimeo.com/717013113) that explains why the polygons aren't located around the green dot and are still valid

**Comment by intractabilis** [comment]
Got it. I assumed that NFP is a Minkowski difference, which is true only if the reference point is at the coordinate (0, 0). Thank you for clarification. Nice video!

**Comment by kallaballa** [comment]
:)
