### ISSUE TITLE
it seems like there is a bug

### ISSUE THREAD

**Issue by optastar** [kallaballa/libnfporb#32]
![bug](https://user-images.githubusercontent.com/19282325/203973306-f181e9c7-acde-4ade-8c7b-d5e80c17656d.png)

testdata:
POLYGON((172 143, 142 117, 112 91, 82 65, 52 39,  52 31, 52 23, 52 15, 52 06, 314 06, 576 06, 837 06, 1099 06, 1099 15, 1099 23, 1099 31, 1099 39, 1069 65, 1039 91, 1009 117, 979 143, 964 118, 944 98, 919 83, 892 75, 734 53, 576 46, 417 53, 259 75, 259 75, 232 83, 207 98, 187 118, 172 143))

**Comment by kallaballa** [comment]
I'm sorry, at the moment I don't have time to investigate this bug. I'll get back to you as soon as possible.

**Comment by kallaballa** [comment]
There are way better alternatives out by now that is why I'm going to archive this repository
