### ISSUE TITLE
How to generate an inside nfp?

### ISSUE THREAD

**Issue by martinhansdk** [kallaballa/libnfporb#4]
Given the polygon for a part and the polygon for a bin in which the part should be placed, how can I generate the nfp on the inside of the bin?

If I do 

`nfp_t nfp = generateNFP(bin, part, true);`

Then it gives me the nfp for placing the part on the outside of the bin.

**Comment by kallaballa** [comment]
I think there is a misunderstanding in what the NFP is. The NFP is the result of sliding two (parts) polygons around each other to make overlap testing less computational expensive. There is no bin involved.

**Comment by martinhansdk** [comment]
I think I understand that, although I may be wrong. What I am trying to do is to generate an NFP for the polygon `part` sliding around the inside of the polygon `bin`. libnfporb already supports polygons with holes in them and I want it to treat `bin` as a hole.

The background is that when writing a nester there has to be an outer boundary, the bin, and all the parts need to be constrained to be placed inside this bin. An nfp of the part sliding inside the bin would give me this (pseudo C++ code):

    nfp_t combined_nfp;
    for(polygon_t placed_part : already_placed_parts) {
        nfp_t part_nfp = generateNFP(placed_part, unplaced_part);
        combined_nfp = union(combined_nfp, part_nfp);
    }
    combined_nfp = difference(generateInsideNFP(bin, unplaced_part), combined_nfp);

With this I have all the possible placements for part `unplaced_part` such that it does not overlap with any of the `already_placed_parts`, does not overlap with `bin` and is located inside `bin`.

Does this make sense?

**Comment by kallaballa** [comment]
I understand now what you want to do, but it is not really supported by libnfporb. the only thing you could do is define the bin as a polygon with a hole:
![binhole](https://user-images.githubusercontent.com/287266/39662882-33819602-5069-11e8-87bb-6506ca0943b5.png)
But then you would still have to remove the outter nfp somehow. 
The implementations i know calculate a bounding box for each of the parts and use trigonometry to check if the parts are inside the bin.

**Comment by martinhansdk** [comment]
Thank you. I guess that would work, although it is a little inefficient. I'll do it like this for now.
