### ISSUE TITLE
out_of_range in vector indexing access

### ISSUE THREAD

**Issue by martinhansdk** [kallaballa/libnfporb#8]
In Visual Studio 2017 I run into a situation where the second line of the following code in `selectNextTranslationVector()` causes an `out_of_range` exception:

    if (i >= rA.size())
        next = rA[i % rA.size() + 1];
    else
        next = rA[i];

In my case, `rA.size()` is 5 and `i` is 9. This ends up causing access to `rA[5]` which does not exist.

To reproduce the situation with gcc replace the lines (there are two occurrences of this code in `selectNextTranslationVector()` and another in `searchStartTranslation()`) with 

    next = rA.at(i % rA.size() + 1);

and run the tests.

**Comment by kallaballa** [comment]
Indeed. Fixed with 71e58da01b6ee35f8deb560c4ee91ba05b487c84
