### ISSUE TITLE
removeCoLinear makes polygon invalid

### ISSUE THREAD

**Issue by martinhansdk** [kallaballa/libnfporb#9]
Attached is [colinear.zip](https://github.com/kallaballa/libnfporb/files/2010590/colinear.zip) which causes the error

    terminate called after throwing an instance of 'std::runtime_error'
      what():  Polygon A is invalid: Geometry is defined as closed but is open

As far as I can tell it is because removeCoLinear removes some of the segments so the first and last point of the polygon end up to be different. Calling `bg::correct()` on the resulting polygon seems to fix it.

**Comment by kallaballa** [comment]
Sorry for the long wait :).
I incorporated your test case and your solution. c04e0cf2d6c63b89a28fcff18a9ba911cf51bc7b

Thank you!
